### PR TITLE
macOS 10.12 Sierra support

### PR DESCRIPTION
**Pull request by mikker**
Frustrated about not being able to build the app on the Sierra beta I took a look at what was needed. Turns it wasn't that much.

This will build without errors and work fine on 10.12. I am unsure about what it means for backwards compatibility though.

Thanks!

### CODE REVIEW

**Comment by bambu** [comment]
This commit does not build on Osx 10.11

Here's the relevant part:
```bash
clang++ -o build/input.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/input.mm
src/input.mm:42:9: error: use of undeclared identifier 'NSEventTypeKeyUp'; did you mean 'NSEventTypeSwipe'?
    if (NSEventTypeKeyUp == type && NSEventModifierFlagControl & flags && 48 == [event keyCode]) {
        ^~~~~~~~~~~~~~~~
        NSEventTypeSwipe
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:49:5: note: 'NSEventTypeSwipe' declared here
    NSEventTypeSwipe   NS_ENUM_AVAILABLE_MAC(10_5)       = 31,
    ^
src/input.mm:42:37: error: use of undeclared identifier 'NSEventModifierFlagControl'
    if (NSEventTypeKeyUp == type && NSEventModifierFlagControl & flags && 48 == [event keyCode]) {
                                    ^
2 errors generated.
scons: *** [build/input.o] Error 1
make: *** [all] Error 2
```

It seems that `NSEventTypeKeyUp` and `NSEventModifierFlagControl` are both added in macOS 10.12

**Comment by mikker** [comment]
Maybe this will work, @bambu ?

**Comment by bambu** [comment]
That still didn't build. very similar error if not the same. How about this:

```diff
diff --git a/src/input.mm b/src/input.mm
index 3b63320..7eba3b5 100644
--- a/src/input.mm
+++ b/src/input.mm
@@ -39,21 +39,15 @@
 
     /* <C-Tab> & <C-S-Tab> do not trigger keyDown events.
        Catch the key event here and pass it to keyDown. */
-    if ([[NSProcessInfo processInfo] operatingSystemVersion].minorVersion <= 11) {
-#pragma clang diagnostic push
-#pragma clang diagnostic ignored "-Wdeprecated-declarations"
-      if (NSKeyDown == type && NSControlKeyMask & flags && 48 == [event keyCode]) {
-          [self keyDown:event];
-          return YES;
-      }
-#pragma clang diagnostic pop
-    } else {
-      if (NSEventTypeKeyDown == type && NSEventModifierFlagControl & flags && 48 == [event keyCode]) {
-          [self keyDown:event];
-          return YES;
-      }
-    }
-   
+#ifdef __MAC_10_12
+  if (NSEventTypeKeyDown == type && NSEventModifierFlagControl & flags && 48 == [event keyCode]) {
+#else
+  if (NSKeyDown == type && NSControlKeyMask & flags && 48 == [event keyCode]) {
+#endif
+      [self keyDown:event];
+      return YES;
+  }
+
     return NO;
 }
```

**Comment by mikker** [comment]
I thought I had searched everywhere for a macro like that 😀 
Thanks! Works flawlessly with your patch.

**Comment by bambu** [comment]
No worries. I only know it because i've used it before. You want to modify your PR or should I make another?

**Comment by mikker** [comment]
If this is fine for you then it's also fine for me.

**Comment by james2doyle** [comment]
I actually cant run the latest version after this commit. The app will build fine, but will hang and never start the window

**Comment by bambu** [comment]
@james2doyle, that seems odd. This code change shouldn't cause anything like that. I too am on 10.11.5. 

Here are a few things to try:
1. Are you able to revert to the previous commit, build and run just fine? 
2. By "hang and never start the window" do you mean that you get a grey window with nothing on it?
3. If you press any keys (enter for example) does it pop up? 
4. If you just run nvim from command line do you get any messages?

Finally, what version of Neovim are you running?

**Comment by james2doyle** [comment]
The app shows up in the dock, but a window never appears and the app never
focuses. I have to force close it after about a minute.

Maybe I should mention I'm installing via brew. I used `brew install --HEAD
neovim-dot-app`.

I upgraded neovim before trying to update the app. Also, no messages
running neovim from the command line.

**Comment by bambu** [comment]
@james2doyle how about now?

**Comment by james2doyle** [comment]
😖 

Still busted. Here is my Console.app while running:

screen shot 2016-07-14 at 8 05 47 pm

Not sure if that helps

**Comment by james2doyle** [comment]
Hey man. Really sorry about this but I restarted on a whim, and now it works. I didn't _turn it on and off again_. Again, sorry!

**Comment by rogual** [comment]
OSX does maintain backwards compatibility — correct solution would be to use `-mmacosx-version-min` compile flag (or possibly one of the defines; can't remember right now) and continue using the old constants.

**Comment by bambu** [comment]
@rogual is correct. I had forgotten about that flag. I originally suggested `__MAC_10_12` because i remembered it being in use in the current code base for a different version. Looking at it shows that it had its specific use case. Since the minimum requirements for Neovim.app (according to README) is `10.9`, having `-mmacosx-version-min=10.9` is the better answer so that we don't run into these issues any more.
